return {
  "nvim-treesitter/nvim-treesitter",
  build = ":TSUpdate",
  main = "nvim-treesitter.configs",
  opts = {
    ensure_installed = {
      "lua",
      "javascript",
      "typescript",
      "vimdoc",
      "vim",
      "regex",
      "toml",
      "json",
      "gitignore",
      "yaml",
      "markdown",
      "markdown_inline",
      "bash",
      "tsx",
      "css",
      "html",
      "markdown",
      "markdown_inline",
      "latex",
    },
    auto_install = true,
    highlight = {
      enable = true,
      disable = { "json" },
      additional_vim_regex_highlighting = { "ruby" },
    },
    indent = { enable = true, disable = { "ruby", "json", "markdown" } },
  },
}
